service: pge
provider:
  name: aws
  runtime: nodejs14.x
  profile: rwdvs

stage: dev
region: us-east-1

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: "{proxy+}"
          method: any
          cors: true

plugins:
  - serverless-offline
